[General]
    # What should be the maximum width of an elevator cabin? Higher numbers may cause lag.
    # Allowed range: 1 ~ 15 - Default: 11
    maxCabinHorizontalSize = 7

    # What should be the maximum height of an elevator cabin? Higher numbers may cause lag.
    # Allowed range: 1 ~ 15 - Default: 11
    maxCabinVerticalSize = 7

    # Is the elevator allowed to move unbreakable blocks? If set to true, this may allow players to move blocks like bedrock and portals using elevators!
    # Allowed values: true, false - Default: false
    allowUnbreakableBlocks = false

